repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # renovate: datasource=github-tags depName=pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0 # pragma: allowlist secret
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/Yelp/detect-secrets
    # renovate: datasource=github-releases depName=Yelp/detect-secrets
    rev: 01886c8a910c64595c47f186ca1ffc0b77fa5458 # v1.5.0 # pragma: allowlist secret
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: terraform.tfstate

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    # renovate: datasource=github-releases depName=woodruffw/zizmor-pre-commit
    rev: 07a06156e31897fbb5ba0e22a961e8e3c2a0677b # v1.6.0 # pragma: allowlist secret
    hooks:
      - id: zizmor

  - repo: https://github.com/golangci/golangci-lint
    # renovate: datasource=github-releases depName=golangci/golangci-lint
    rev: eabc2638a66daf5bb6c6fb052a32fa3ef7b6600d # v2.1.6 # pragma: allowlist secret
    hooks:
      - id: golangci-lint

  - repo: local
    hooks:
      - id: go-unit-tests
        name: go unit tests
        entry: go test ./...
        pass_filenames: false
        types: [go]
        language: system
